service: aws-lambda-twitter-personal-bot

provider: 
    name: aws
    runtime: nodejs10.x # Node JS version
    memorySize: 512
    timeout: 15
    stage: production
    role: arn:aws:iam::485947658225:role/Serverless-twitter-atique-bot
    region: ap-south-1 # AWS region

functions:
 api:
   handler: handler.twitterBot